### ISSUE TITLE
Change private key type from string to UInt8Array for projects/portal

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [UnUniFi/web-apps#15]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Reflect https://github.com/UnUniFi/utils/pull/207 to projects/portal in this repository

**Describe alternatives you've considered**

**Additional context**

**Comment by taro04** [comment]
Search the project with `privatekey:` and confirm that the private key type is UInt8Array
