### ISSUE TITLE
Created or imported account is not saved in IndexedDB on alpha-test portal environment

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [UnUniFi/web-apps#150]
**Describe the bug**

On alpha-test portal ( https://alpha-test.ununifi.io/portal/ ), created or imported account is not saved in IndexedDB.

Following error message is shown in browser's console.

```
TypeError: Cannot destructure property 'primaryKey' of 'e' as it is undefined.
```

**To Reproduce**

1. Go to https://alpha-test.ununifi.io/portal/
2. Click on 'Connect Wallet' and create or import account
3. before close complete dialog, error is shown in console

**Expected behavior**

No error and the account should be saved in IndexedDB.

**Screenshots**

![image](https://user-images.githubusercontent.com/55148923/167756399-42df719e-fff0-4ce0-bade-7ae49efc0b5c.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [101.0.4951.54]

**Additional context**

- On beta-test portal ( https://beta-test.ununifi.io/portal/ ), the issue is not reproduced. In other words, is the cause in the difference between the current develop and main branches? (or deploy timing? I'm not sure...)
- Fundamentally, it is due to the messy error handling of the set* methods in the WalletInfrastructureService.

**Comment by Senna46** [comment]
I reproduced this problem myself in https://alpha-test.ununifi.io/portal/ 
But, it works in develop branch that run on local. Not sure if it's really a code problem.

**Comment by YasunoriMATSUOKA** [comment]
I guess the issue is not reproduced with ng serve, but it is reproduced with firebase emulator.

**Comment by Senna46** [comment]
I've tried `npm run start:all`, but there is no problem...

**Comment by YasunoriMATSUOKA** [comment]
In my environment, the issue is reproduced with `npm run start:all`

![image](https://user-images.githubusercontent.com/55148923/167769501-c44e8bbd-f125-489d-a0c2-6a6e7f970824.png)

**Comment by Senna46** [comment]
I was looking in the wrong place, sorry. You are right, there is a problem.

**Comment by YasunoriMATSUOKA** [comment]
I am curious, with same code, when I debug with `npm run start:portal`, the problem does not seem to be reproduced...

I guess the following points are related, but I'm not sure...

1. ng serve or firebase emulator?
2. ng serve or ng build
3. dev config or prod config

**Comment by YasunoriMATSUOKA** [comment]
fixed. but at this point, I don't know why the PR is bad...
