### ISSUE TITLE
Implement fee validation and notification for projects/portal

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [UnUniFi/web-apps#17]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Reflect https://github.com/UnUniFi/utils/pull/207 to projects/portal in this repository

**Describe alternatives you've considered**

**Additional context**

**Comment by taro04** [comment]
This is probably done, but I can't confirm it because the CDP is incomplete. 
After completing the CDP implementation, check the private key validation, then close it.
