### ISSUE TITLE
Handle errors of the cases Keplr is not installed or Keplr is not unlock

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [UnUniFi/web-apps#201]
**Describe the bug**

https://github.com/UnUniFi/web-apps/pull/200#issuecomment-1144444835

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Oluwatammie** [comment]
Try using an higher version of iOS and if it an Android Yu are using try using a minimum of Android version 10.  Butt if the error still persists it means that your IP isn't supported by keplr
