### ISSUE TITLE
Why `metaMask` is lower camel case?

### ISSUE THREAD

**Issue by KimuraYu45z** [UnUniFi/web-apps#208]
**Describe the bug**

`projects/portal/src/app/models/wallets/wallet.model.ts`

I think Metamask should be `"MetaMask"`, upper camel case. This data is used in display, so when this lower camel case is displayed in the UI, it is little strange.

`UnUniFi`, `Keplr`, `Ledger`, `KeyStation` is also same.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by japui** [comment]
Dispositivo: [por exemplo, iPhone6]
SO: [por exemplo, iOS8.1] teria o mesmo efeito com outro iPhone ou Android.
