### ISSUE TITLE
Migrate PR UnUniFi/utils/pull/229 from utils/projects/telescope-extension to portal

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [UnUniFi/web-apps#22]
**Is your feature request related to a problem? Please describe.**

https://github.com/UnUniFi/utils/pull/229

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by taikiFurusyo** [comment]
It's done at #24 and #26.
