### ISSUE TITLE
feat: claimable reward location and text revision

### ISSUE THREAD

**Issue by taiki1frsh** [UnUniFi/web-apps#231]
1) I want to see Claimable reward on balance page.
2) Withdraw should be Claim.

![a3dc86fc959edb6c](https://user-images.githubusercontent.com/60684182/174736170-f5c49822-7d86-41fd-98e3-67e2799543cc.jpeg)

**Comment by taikiFurusyo** [comment]
The link of the talk which is the location of "Delegations" section.
https://discord.com/channels/762953633230356480/923009658967453736/988713448575750147

**Comment by YasunoriMATSUOKA** [comment]
Thanks.
Will you implement `I want to see Claimable reward on balance page.` on this PR?

**Comment by taikiFurusyo** [comment]
I'm not sure about it.
How about showing "Claimable reward" instead of "Shares" on validators page?

**Comment by YasunoriMATSUOKA** [comment]
I guess balance page is https://ununifi.io/portal/
I guess he insists he want to view his own delegation related info in that page.
But, I'm not sure.
If you can could you ask him?

**Comment by taikiFurusyo** [comment]
> I guess he insists he want to view his own delegation related info in that page. (In my opinion, it is reasonable, I think.)
Yeah, I think so, too.
Should that feature be implemented in PR #232 ?
