### ISSUE TITLE
typo UnUnuFi

### ISSUE THREAD

**Issue by KimuraYu45z** [UnUniFi/web-apps#265]
https://discord.com/channels/762953633230356480/956540286190895194/1011709736212766740

**Comment by yutaro-elk** [comment]
Fixed. 
Confirmed in beta test. (https://beta-test.ununifi.io/portal/) Release to main net.

**Comment by yutaro-elk** [comment]
Fixed
https://github.com/UnUniFi/web-apps/pull/266

Released
https://ununifi.io/portal/

<img width="328" alt="image" src="https://user-images.githubusercontent.com/36399275/186615674-0327d135-b00d-4e21-bd5c-91da06aae5a9.png">
