### ISSUE TITLE
Newly added proposal doesn't show up in both portal and explorer

### ISSUE THREAD

**Issue by taiki1frsy** [UnUniFi/web-apps#268]
**Describe the bug**
Newly added proposal doesn't show up in both portal and explorer

**To Reproduce**
Just post the proposal

**Comment by yutaro-elk** [comment]
Please also include the target network. does it happen at all?

**Comment by taiki1frsy** [comment]
It turns out the problem lies in the way to handle the specific data in SoftWareUpgrade proposal.
The comment on the above was not technically correct.

**Comment by Senna46** [comment]
The function returns raw data when an error occurs in cosmos-client-ts. This is a temporary fix. There should be no particular problem with the display.

Originally, cosmos-client is not needed here, so it may be deleted.

@taiki1frsy 
I think we can merge this, but what do you think?
Certainly, cosmos-client-ts has a bug, but it is not the essence of this issue.
