### ISSUE TITLE
BUBBLE: error pop-up message for sending NFT listing tx

### ISSUE THREAD

**Issue by taiki1frsy** [UnUniFi/web-apps#285]
**Is your feature request related to a problem? Please describe.**
Unclear and even it's not a error from the perspective of the chain implementation.

<img width="450" alt="スクリーンショット 2022-09-30 13 30 00" src="https://user-images.githubusercontent.com/60684182/193205426-84e7e1f4-ed9b-4648-bc1a-ac7e858b91ef.png">

**Describe the solution you'd like**
This can be just went through the blank check and fill the cells with the default values.

**Comment by mkXultra** [comment]
maybe done

**Comment by taiki1frsy** [comment]
I saw this specifically fixed.
the error handling should be improved in the future tho.
