### ISSUE TITLE
Provide a way to renew bid amount for those who already made a bid

### ISSUE THREAD

**Issue by taiki1frsh** [UnUniFi/web-apps#297]
Currently, we don't have renew bid option.
The goal is to provide a way to achieve it without canceling bid.

**Comment by mkXultra** [comment]
fixed

**Comment by mkXultra** [comment]
You can bid again on the bidding screen

**Comment by taiki1frsy** [comment]
I confirmed it's provided.
![スクリーンショット 2022-10-28 12 54 11](https://user-images.githubusercontent.com/60684182/198498837-5d5352f2-d814-4da2-8e69-343339fdb565.png)

But, I guess the word better being changed.
How about "Renew my bid" or something like this?
