### ISSUE TITLE
review for new UI on Bubble nft market

### ISSUE THREAD

**Issue by mkXultra** [UnUniFi/web-apps#304]

**Comment by mkXultra** [comment]
can't move to mypage from nft list
https://ununifi-marketplace.bubbleapps.io/version-ui-update/nft_collection_detail?debug_mode=true&class_id=ununifi-13E8E825E47E49C548ACA780FD62DEC269542C8F

**Comment by mkXultra** [comment]
I can't access my page nft detail

**Comment by mkXultra** [comment]
I can't access　nft detail

**Comment by mkXultra** [comment]
I can't click to Place bid from nft_collection_detail

**Comment by mkXultra** [comment]
remove scroll bar.
![キャプチャ](https://user-images.githubusercontent.com/34665721/200466546-a09dfcd3-c705-4da1-a1f5-060013cdfeb5.PNG)

**Comment by Senna46** [comment]
- [ ] 出品
- [ ] 出品キャンセル
- [ ] Borrow
- [ ] Repay
- [ ] 出品延長
- [ ] 落札者決定
- [ ] 入札
- [ ] 入札キャンセル
- [ ] 再入札
- [ ] pay
