### ISSUE TITLE
Update "connect wallet" button once user connects

### ISSUE THREAD

**Issue by taiki1frsh** [UnUniFi/web-apps#333]
The "connect wallet" button on the left above page is even on after connecting wallet.
We should 
1. Just show connected address
2. Show wallet option user used and show address
, I think.

@Senna46 
What  do you think?

**Comment by Senna46** [comment]
The UI was initially for account switching. Should it be changed? Maybe we could at least change the button display text.

**Comment by taiki1frsh** [comment]
better to show the shorten address, then?

**Comment by Senna46** [comment]
It is fixed on https://github.com/UnUniFi/web-apps/pull/320/commits/1e8e7f6a0dcdb61f1e6bbbc369f3bd195a93aed2

**Comment by taiki1frsh** [comment]
@Senna46 
sorry, didn't notice that.
I just reviewed it. Plz check.
