### ISSUE TITLE
Loading animation does not end after a successful faucet request

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [UnUniFi/web-apps#54]
**Describe the bug**

Loading animation does not end after a successful faucet request.

**To Reproduce**

**Expected behavior**

After a successful faucet request, loading animation should end.

**Screenshots**

**Desktop (please complete the following information):**

![image](https://user-images.githubusercontent.com/55148923/162103176-e576ee5e-09c0-44ba-b0aa-3eac648c3247.png)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Senna46** [comment]
I tried, but there is a problem #53 and have the following error.
Should I wait for a fix for this?
`Error: invalid Bech32 prefix; expected ununifi, got cosmos`

**Comment by YasunoriMATSUOKA** [comment]
No. You don't need to wait for that fix.
You can set your correct address manually, so you can debug the page with manual correct address input.

I guess https://github.com/UnUniFi/web-apps/pull/32 will fix wrong prefix issue ( https://github.com/UnUniFi/web-apps/issues/53 ), but will not fix following screenshot issue (=this issue).
https://user-images.githubusercontent.com/55148923/162103176-e576ee5e-09c0-44ba-b0aa-3eac648c3247.png

**Comment by Senna46** [comment]
ok
i reproduced the problem. thx.
