### ISSUE TITLE
Some items are not displayed in transactions

### ISSUE THREAD

**Issue by taro04** [UnUniFi/web-apps#88]
**Describe the bug**

Some items are not displayed when displaying tx other than transfar.

**To Reproduce**
for example, PostPrice
[http://localhost:4200/explorer/blocks/426198](http://localhost:4200/explorer/blocks/426198)

**Expected behavior**

Extract all types that may be displayed.
Decide which item to display for all types.
Unpack and retrieve and display any item for all transaction types.

**Screenshots**
![image](https://user-images.githubusercontent.com/75844498/164010080-9fa9b451-e318-4d04-a029-42d6334f6d60.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by YasunoriMATSUOKA** [comment]
fixed
