### ISSUE TITLE
Not compatible with v0.45.1

### ISSUE THREAD

**Issue by Senna46** [UnUniFi/web-apps#9]
**Describe the bug**
When I compile the cosmos-client and unifi-client versions used are 0.45.1, the following error occurs in some places.

ex.
```
Error: projects/portal/src/app/utils/function.ts:43:63 - error TS2551: Property 'debt_param' does not exist on type 'IParams'. Did you mean 'debt_params'?

43   const principalConversionFactor = Number.parseInt(cdpParams.debt_param?.conversion_factor || '0');
                                                                 ~~~~~~~~~~

  node_modules/ununifi-client/cjs/proto.d.ts:2998:13
    2998             debt_params?: (ununifi.cdp.IDebtParam[]|null);
                     ~~~~~~~~~~~
    'debt_params' is declared here.
```

**To Reproduce**
1. In `pakage.json` change cosmos-client & ununifi-client version v0.44.x => v0.45.1
2. Run `npm i`
3. Run `npm run start:portal`
 
**Expected behavior**
Compilation succeeds without error

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by YasunoriMATSUOKA** [comment]
Migrate to https://github.com/UnUniFi/web-apps/issues/22 and Close
